services:
  postgres-db:
    container_name: postgres-db
    build:
      context: ./src/database/
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: 'rss_node_service'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '7postgres7'
    env_file:
      - .docker.env
    ports:
      - '$POSTGRES_PORT:$POSTGRES_PORT'
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app-db-network

  app:
    container_name: 'restapi-app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '$PORT:$PORT'
    command: npm run start:docker:dev
    volumes:
      - .:/app
    env_file:
      - .docker.env
    depends_on:
      - postgres-db
    restart: on-failure
    networks:
      - app-db-network

networks:
  app-db-network:
    driver: bridge

volumes:
  dbdata:
